on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      application-name:
        required: true
        type: string

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: extractions/setup-just@v1

    - name: Unit tests
      run: just unit-tests

    - name: build artifact
      run: just build

    - name: push artifact
      run: just push

  Deploy-Preview:
    if: inputs.ref != 'refs/heads/main'
    needs: [Build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: extractions/setup-just@v1
    - name: deploy edge
      run: just deploy edge

    - name: integration tests edge
      run: just integration-tests edge


  Deploy-Edge:
    if: inputs.ref == 'refs/heads/main'
    needs: [Build]
    runs-on: ubuntu-latest
    environment:
      name: edge
      url: https://${{ inputs.application-name }}.internal.edge.europe-west4.interface.trv.cloud
    steps:
    - uses: actions/checkout@v3
    - uses: extractions/setup-just@v1
    - name: deploy edge
      run: just deploy edge

    - name: integration tests edge
      run: just integration-tests edge

  Deploy-Stage:
    if: inputs.ref == 'refs/heads/main'
    needs: [Deploy-Edge]
    runs-on: ubuntu-latest
    environment:
      name: stage
      url: https://${{ inputs.application-name }}.internal.stage.europe-west4.interface.trv.cloud
    steps:
    - uses: actions/checkout@v3
    - uses: extractions/setup-just@v1
    - name: deploy stage
      run: just deploy stage

    - name: integration tests stage
      run: just integration-tests stage

  Deploy-Prod:
    if: inputs.ref == 'refs/heads/main'
    needs: [Deploy-Stage]
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: https://${{ inputs.application-name }}.internal.prod.europe-west4.interface.trv.cloud
    steps:
    - uses: actions/checkout@v3
    - uses: extractions/setup-just@v1
    - name: deploy prod
      run: just deploy prod
      
    - name: integration tests prod
      run: just integration-tests prod