on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      application-name:
        required: true
        type: string
      target-cluster:
        required: true
        type: string
      working-directory:
        required: false
        type: string
        default: .


jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: extractions/setup-just@v1

    - name: Unit tests
      run: just unit-tests
      working-directory: ${{ inputs.working-directory }}

    - name: build artifact
      run: just build
      working-directory: ${{ inputs.working-directory }}

    - name: push artifact
      run: just push
      working-directory: ${{ inputs.working-directory }}

  Deploy-Preview:
    if: inputs.ref != 'refs/heads/main'
    needs: [Build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: extractions/setup-just@v1
    - name: deploy edge
      run: just deploy edge
      working-directory: ${{ inputs.working-directory }}

    - name: integration tests edge
      run: just integration-tests edge
      working-directory: ${{ inputs.working-directory }}


  Deploy-Edge:
    if: inputs.ref == 'refs/heads/main'
    needs: [Build]
    runs-on: ubuntu-latest
    environment:
      name: "${{ inputs.application-name }} edge"
      url: https://${{ inputs.application-name }}.internal.edge.europe-west4.${{ inputs.target-cluster }}.trv.cloud
    steps:
    - uses: actions/checkout@v3
    - uses: extractions/setup-just@v1
    - name: deploy edge
      run: just deploy edge
      working-directory: ${{ inputs.working-directory }}

    - name: integration tests edge
      run: just integration-tests edge
      working-directory: ${{ inputs.working-directory }}

  Deploy-Stage:
    if: inputs.ref == 'refs/heads/main'
    needs: [Deploy-Edge]
    runs-on: ubuntu-latest
    environment:
      name: "${{ inputs.application-name }} stage"
      url: https://${{ inputs.application-name }}.internal.stage.europe-west4.${{ inputs.target-cluster }}.trv.cloud
    steps:
    - uses: actions/checkout@v3
    - uses: extractions/setup-just@v1
    - name: deploy stage
      run: just deploy stage
      working-directory: ${{ inputs.working-directory }}

    - name: integration tests stage
      run: just integration-tests stage
      working-directory: ${{ inputs.working-directory }}

  Deploy-Prod:
    if: inputs.ref == 'refs/heads/main'
    needs: [Deploy-Stage]
    runs-on: ubuntu-latest
    environment:
      name: "${{ inputs.application-name }} prod"
      url: https://${{ inputs.application-name }}.internal.prod.europe-west4.${{ inputs.target-cluster }}.trv.cloud
    steps:
    - uses: actions/checkout@v3
    - uses: extractions/setup-just@v1
    - name: deploy prod
      run: just deploy prod
      working-directory: ${{ inputs.working-directory }}
      
    - name: integration tests prod
      run: just integration-tests prod
      working-directory: ${{ inputs.working-directory }}