on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: extractions/setup-just@v1

    - name: Unit tests
      run: just unit-tests

    - name: build artifact
      run: just build

    - name: push artifact
      run: just push

  Deploy-Edge:
    needs: [Build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: extractions/setup-just@v1
    - name: deploy edge
      run: just deploy edge

    - name: integration tests edge
      run: just integration-tests edge

  Deploy-Stage:
    needs: [Deploy-Edge]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: extractions/setup-just@v1
    - name: deploy stage
      run: just deploy stage

    - name: integration tests stage
      run: just integration-tests stage

  Deploy-Prod:
    if: inputs.head-ref == 'refs/heads/main'
    needs: [Deploy-Stage]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: extractions/setup-just@v1
    - name: deploy prod
      run: just deploy prod
      
    - name: integration tests prod
      run: just integration-tests prod