on:
  workflow_call:
    inputs:
      git-rev:
        required: true
        type: string

jobs:
  Build-Release:
    runs-on: ubuntu-latest
    steps:
    - name: build
      run: |
        echo "I'd invoke jest build with ${{ inputs.git-rev }}"
